FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y cron && \
    pip install --upgrade pip && pip install -r requirements.txt && \
    python -m spacy download en_core_web_sm

COPY cronjob/crontab.txt /etc/cron.d/mycron
RUN chmod 0644 /etc/cron.d/mycron && crontab /etc/cron.d/mycron

COPY cronjob/docker-cron-entry.sh /docker-cron-entry.sh
RUN chmod +x /docker-cron-entry.sh

CMD [\"/docker-cron-entry.sh\"]
