name: Render Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Hook
        run: curl -X POST ${{ https://api.render.com/deploy/srv-cvr4ldfgi27c738l2pj0?key=LXbM54aOWUc }}
