name: CI - Run Tests

# ここが最上部のトリガー設定
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'   # 毎時0分に実行（UTC）。必要に応じて時刻を調整してください。

jobs:
  test:
    runs-on: windows-latest  # Windows環境でテストを実行（必要に応じて ubuntu-latest などに変更も可能）
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: python -m pytest
