name: Run App Process

# トリガーの設定
on:
  schedule:
    - cron: '0 * * * *'      # 毎時0分に実行（UTC時間、必要に応じて時刻を調整）
  workflow_dispatch:         # GitHub上で手動実行できるようにする

jobs:
  run_app:
    runs-on: ubuntu-latest   # Linux環境での実行（無料枠が無制限に近い）
    steps:
      # ① リポジトリの最新コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # ② Python のセットアップ
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # ③ 依存パッケージのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ④ アプリケーション（本番モード）の実行
      - name: Run application in production mode
        run: |
          python app.py --mode production

      # ⑤ 成果物のアップロード（任意）
      - name: Upload processed data artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: output/  # app.py で保存された成果物のディレクトリ
